import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import Banner from "@/components/Banner";
import Earn from "@/components/Earn";
import { Footer } from "@/components/Footer";
import CardSection from "@/Section/CardSection";
import { useTranslation } from "react-i18next";
import useStore from "@/store/useStore";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { getProductListApi } from "@/services/productService";

const Home: NextPage = () => {
  const { t } = useTranslation("common");
  const { updateProductArray } = useStore();
  const router = useRouter();
  const { inviteCode } = router.query;

  useEffect(() => {
    const fetchProductList = async () => {
      const products = await getProductListApi();
      updateProductArray(products);
    };

    fetchProductList();
  }, [updateProductArray]);

  useEffect(() => {
    if (inviteCode) {
      localStorage.setItem("inviteCode", inviteCode as string);
    } else {
      localStorage.removeItem("inviteCode");
    }
  }, [inviteCode]);

  return (
    <div>
      <Head>
        <title>{t("earn")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab type="fixed" tabType="normal" />
      <Banner />
      <CardSection />
      <Earn col />
      <Footer />
    </div>
  );
};

export default Home;
