import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import PointsMarketSection from "@/Section/PointsMarketSection";
import LevelSection from "@/Section/LevelSection";

const Market: NextPage = () => {
    return (
        <div>
            <Head>
                <title>RainbowKit App - Market</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <Header logo switchTab />
            <LevelSection />
            <Footer />
        </div>
    );
};

export default Market;
