import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import PointsMarketSection from "@/Section/PointsMarketSection";
import { useTranslation } from "react-i18next";
import useStore from "@/store/useStore";
import { useEffect } from "react";
import { useGetUserInfoByAddress } from "@/services/useGetUserInfoByAddress";
import Loading from "@/components/Loading";

const Market: NextPage = () => {
  const { t } = useTranslation("common");
  const { userInfo, updateIntegralInfo } = useStore();
  const { data, loading, error } = useGetUserInfoByAddress(
    userInfo?.address || ""
  );

  useEffect(() => {
    if (data && data.getUser?.user) {
      updateIntegralInfo(data.getUser.user);
    }
  }, [data, updateIntegralInfo]);

  if (loading) return <Loading text={"Points Loading"} />;
  if (error) return <div>Error loading data</div>;

  return (
    <div>
      <Head>
        <title>{t("points")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab />
      <PointsMarketSection type="myRewards" />
      <Footer />
    </div>
  );
};

export default Market;
