import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { useTranslation } from "react-i18next";
import { useRouter } from "next/router";

const Privacy: NextPage = () => {
  const { t } = useTranslation("privacy");
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>{t("privacy-title-1")}</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header logo switchTab />
      <section className="bg-bg-primary w-full py-8 sm:py-[135px] px-4 sm:px-8 md:px-12 lg:px-[105px]">
        <h1 className="text-2xl sm:text-4xl font-bold text-primary mb-6 sm:mb-8">
          {t("privacy-title-1")}
        </h1>

        <div className="space-y-4 sm:space-y-6">
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-2")}
          </p>

          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-3")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-4")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-5")}
          </p>

          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-6")}
          </p>

          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-7")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-8")}
          </h2>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-9")}
          </h2>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-10")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-11")}
          </p>

          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-12")}
          </p>

          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-13")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-14")}
          </h2>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-15")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-16")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-17")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-18")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-19")}
          </h2>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-20")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-21")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-22")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-23")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-24")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-25")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-26")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-27")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-28")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-29")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-30")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-31")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-32")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-33")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-34")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-35")}
          </p>

          <h2 className="text-lg sm:text-2xl font-semibold mb-1 sm:mb-2">
            {t("privacy-title-36")}
          </h2>
          <p className="text-sm sm:text-base text-primary leading-relaxed">
            {t("privacy-content-37")}
          </p>

          <p
            className="text-base font-semibold mb-1 sm:mb-2 text-right cursor-pointer hover:text-[#FFD700]"
            onClick={() => router.push("/privacy")}
          >
            {t("privacy-title-38")}
          </p>
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default Privacy;
